system:
  name: "RAG System"
  version: "0.1"

paths:
  documents_dir: "../documents"
  models_dir: "models"

templates:
  prompt_template: "prompt_template_eng"

embedding:
  models: "intfloat/multilingual-e5-large"
  batch_size: 32

gliner:
  ticket: "urchade/gliner_multi-v2.1"
  threshold: 0.6
  local_only: False

gliner2:
  ticket: "fastino/gliner2-base-v1"
  threshold: 0.3

graph:
  extractor_prompt: "template_two"
  limit: 10

rag:
  chunk_size: 2000
  chunk_overlap: 150
  retrieval_limit: 5
  temperature: 0.5
  top_p: 0.9
  max_length: 1500

llm_local:
  model: "Qwen/Qwen3-4B-Instruct-2507"
  max_new_tokens: 2000

ollama:
  model: "llama3.2:latest"
  url: "http://localhost:11434"
  timeout: 60
  temperature: 0.5
  top_p: 0.9
  max_length: 1500

external_service:
  model: "openai/gpt-4o"
  url: "https://openrouter.ai/api/v1"
  api_key: ""

giga:
  authorization: ""
  uuid: ""