system:
  name: "RAG System"
  version: "0.1"

paths:
  documents_dir: "../documents"
  models_dir: "models"
  prompts_templates:
    extraction_template: "extraction_template_eng"
    prompt_template: "prompt_template"

models:
  embedding: "intfloat/multilingual-e5-large"
  llm: "llama3.2:latest"

gliner:
  ticket: "urchade/gliner_multi"
  threshold: 0.1

graph:
  prompts: "prompts_templates/extraction_template"
  limit: 10

rag:
  chunk_size: 1000
  chunk_overlap: 150
  retrieval_limit: 5
  temperature: 0.5
  top_p: 0.9
  max_length: 1500

ollama:
  url: "http://localhost:11434"
  timeout: 60
  temperature: 0.5
  top_p: 0.9
  max_length: 1500